sudo: required
language: java
jdk:
- oraclejdk8
install: ./spigotSetup.sh
script: mvn clean install -U
<<<<<<< HEAD
deploy:
  provider: releases
  api_key: "$GITHUB_OAUTH_TOKEN" 
  file: target/bukkit-1.0-SNAPSHOT.jar
  on:
    repo: McTournaments/Bukkit
=======
>>>>>>> d4f81bd83ba6d56a83e6d4b5ee551d780f1fc477
